//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeigthWatcher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.PatientDetails = new HashSet<PatientDetail>();
        }
    
        public int PatientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Description { get; set; }
        public int AddressId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public Nullable<double> Height { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDetail> PatientDetails { get; set; }
    }
}
