//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeigthWatcher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TreatementType()
        {
            this.Treatement2Patient = new HashSet<Treatement2Patient>();
            this.TreatementTypes1 = new HashSet<TreatementType>();
        }
    
        public int TreatementTypeId { get; set; }
        public string TreatementTypeName { get; set; }
        public int TreatementTypeParentId { get; set; }
        public string TreatementTypeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treatement2Patient> Treatement2Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TreatementType> TreatementTypes1 { get; set; }
        public virtual TreatementType TreatementType1 { get; set; }
    }
}
